version: '3'

networks:
    bdnet:
        ipam:
            config:
                - subnet: 10.100.0.0/24

services:
    redis_container_dhaka:
        image: redis
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.6

    redis_container_chittagong:
        image: redis
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.60

    communication_service_dhaka:
        build: ./Comm/
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.3

    communication_service_chittagong:
        build: ./Comm/
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.30

    mongodb_container:
        image: mongo
        restart: always
#        volumes:
#            - mongodb_rating_data:/data/db
        networks:
            bdnet:
                ipv4_address: 10.100.0.5

    ride_service_dhaka:
        build: ./RideMatch/
        restart: always
        depends_on:
            - communication_service_dhaka
            - redis_container_dhaka
        networks:
            bdnet:
                ipv4_address: 10.100.0.2

    ride_service_chittagong:
        build: ./RideMatch/
        restart: always
        depends_on:
            - communication_service_chittagong
            - redis_container_chittagong
        networks:
            bdnet:
                ipv4_address: 10.100.0.20

    rate_service:
        build: ./Rate/
        restart: always
        depends_on:
            - mongodb_container
        networks:
            bdnet:
                ipv4_address: 10.100.0.4

    nginx_dhaka:
        build: ./nginx/
        environment:
            - ride_service=ride_service_dhaka
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
        depends_on:
            - ride_service_dhaka
            - rate_service
        networks:
            bdnet:
                ipv4_address: 10.100.0.10

    nginx_chittagong:
        build: ./nginx/
        environment:
            - ride_service=ride_service_chittagong
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
        depends_on:
            - ride_service_chittagong
            - rate_service
        networks:
            bdnet:
                ipv4_address: 10.100.0.100

#volumes:
#    mongodb_rating_data: